---
jobs:
- id: "first_backup"
  provider: aws.rds.backup
  spec:
    rds_arn: "someArn"
    connection_string: "someConnectionString"
  targets:
  - type: "s3"
    target_spec:
      s3_bucket_name: "my-bucket"
      s3_bucket_key: "staging/backups"
- id: "second_backup"
  provider: local
  spec: 
    path: "somePath"
    extension: "tar"
  targets:
  - type: "s3"
    target_spec:
      s3_bucket_name: "my-bucket"
      s3_bucket_key: "prod/backups"
  - type: local
    target_spec:
      destination_dir: /etc/itsb/backup

